lsi: false
safe: true
source: /home/vincent/Documents/NSI/cours_github/bytRuck22.github.io
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
